-- =============================================================================
-- Zuno development seed - GENERATED by scripts/generate-seed-sql.py from
-- supabase/seed/zuno_seed.json. Do not edit by hand; edit the JSON and re-run.
--
-- !!! LOCAL DEVELOPMENT ONLY !!!
-- * Creates sample auth users (organizer owners + one attendee) with *.example
--   e-mail addresses and the placeholder password 'change-me-locally'.
-- * All organizers, people and events are fictional.
-- * Never run this file against a production project.
-- Event dates are resolved relative to now() in Asia/Colombo local time.
-- =============================================================================

set timezone = 'Asia/Colombo';

-- Local date + offset days + local time -> timestamptz (Asia/Colombo).
create or replace function pg_temp.seed_at(p_offset_days integer, p_time text)
returns timestamptz language sql stable as $$
  select (((now() at time zone 'Asia/Colombo')::date + p_offset_days) + p_time::time) at time zone 'Asia/Colombo'
$$;

-- Agenda items with offset_hours/duration_hours -> {starts_at, ends_at, title, detail}.
create or replace function pg_temp.seed_agenda(p_starts timestamptz, p_items jsonb)
returns jsonb language sql stable as $$
  select coalesce(jsonb_agg(jsonb_build_object(
      'starts_at', p_starts + make_interval(secs => ((i ->> 'offset_hours')::numeric * 3600)::double precision),
      'ends_at', p_starts + make_interval(secs => (((i ->> 'offset_hours')::numeric + (i ->> 'duration_hours')::numeric) * 3600)::double precision),
      'title', i ->> 'title',
      'detail', i ->> 'detail'
    ) order by ord), '[]'::jsonb)
  from jsonb_array_elements(p_items) with ordinality as t(i, ord)
$$;

-- -----------------------------------------------------------------------------
-- LOCAL DEVELOPMENT auth users (password: 'change-me-locally')
-- -----------------------------------------------------------------------------
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
                        raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
                        confirmation_token, recovery_token, email_change_token_new, email_change)
values ('00000000-0000-0000-0000-000000000000', 'a0000000-0000-4000-8000-000000000001', 'authenticated', 'authenticated', 'owner.colombo-builders@zuno.example',
        extensions.crypt('change-me-locally', extensions.gen_salt('bf')), now(),
        '{"provider":"email","providers":["email"]}'::jsonb, '{"display_name":"Colombo Builders Collective Team"}'::jsonb,
        now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('a0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', '{"sub":"a0000000-0000-4000-8000-000000000001","email":"owner.colombo-builders@zuno.example","email_verified":true}'::jsonb, 'email', now(), now(), now())
on conflict (provider_id, provider) do nothing;

insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
                        raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
                        confirmation_token, recovery_token, email_change_token_new, email_change)
values ('00000000-0000-0000-0000-000000000000', 'a0000000-0000-4000-8000-000000000002', 'authenticated', 'authenticated', 'owner.kandy-arts-guild@zuno.example',
        extensions.crypt('change-me-locally', extensions.gen_salt('bf')), now(),
        '{"provider":"email","providers":["email"]}'::jsonb, '{"display_name":"Kandy Arts Guild Team"}'::jsonb,
        now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('a0000000-0000-4000-8000-000000000002', 'a0000000-0000-4000-8000-000000000002', '{"sub":"a0000000-0000-4000-8000-000000000002","email":"owner.kandy-arts-guild@zuno.example","email_verified":true}'::jsonb, 'email', now(), now(), now())
on conflict (provider_id, provider) do nothing;

insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
                        raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
                        confirmation_token, recovery_token, email_change_token_new, email_change)
values ('00000000-0000-0000-0000-000000000000', 'a0000000-0000-4000-8000-000000000003', 'authenticated', 'authenticated', 'owner.island-sound@zuno.example',
        extensions.crypt('change-me-locally', extensions.gen_salt('bf')), now(),
        '{"provider":"email","providers":["email"]}'::jsonb, '{"display_name":"Island Sound Society Team"}'::jsonb,
        now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('a0000000-0000-4000-8000-000000000003', 'a0000000-0000-4000-8000-000000000003', '{"sub":"a0000000-0000-4000-8000-000000000003","email":"owner.island-sound@zuno.example","email_verified":true}'::jsonb, 'email', now(), now(), now())
on conflict (provider_id, provider) do nothing;

insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
                        raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
                        confirmation_token, recovery_token, email_change_token_new, email_change)
values ('00000000-0000-0000-0000-000000000000', 'a0000000-0000-4000-8000-000000000004', 'authenticated', 'authenticated', 'owner.lanka-oss@zuno.example',
        extensions.crypt('change-me-locally', extensions.gen_salt('bf')), now(),
        '{"provider":"email","providers":["email"]}'::jsonb, '{"display_name":"Lanka Open Source Circle Team"}'::jsonb,
        now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('a0000000-0000-4000-8000-000000000004', 'a0000000-0000-4000-8000-000000000004', '{"sub":"a0000000-0000-4000-8000-000000000004","email":"owner.lanka-oss@zuno.example","email_verified":true}'::jsonb, 'email', now(), now(), now())
on conflict (provider_id, provider) do nothing;

insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
                        raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
                        confirmation_token, recovery_token, email_change_token_new, email_change)
values ('00000000-0000-0000-0000-000000000000', 'a0000000-0000-4000-8000-000000000005', 'authenticated', 'authenticated', 'owner.student-tech@zuno.example',
        extensions.crypt('change-me-locally', extensions.gen_salt('bf')), now(),
        '{"provider":"email","providers":["email"]}'::jsonb, '{"display_name":"Student Tech Societies Network Team"}'::jsonb,
        now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('a0000000-0000-4000-8000-000000000005', 'a0000000-0000-4000-8000-000000000005', '{"sub":"a0000000-0000-4000-8000-000000000005","email":"owner.student-tech@zuno.example","email_verified":true}'::jsonb, 'email', now(), now(), now())
on conflict (provider_id, provider) do nothing;

insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
                        raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
                        confirmation_token, recovery_token, email_change_token_new, email_change)
values ('00000000-0000-0000-0000-000000000000', 'b0000000-0000-4000-8000-0000000000aa', 'authenticated', 'authenticated', 'dev.attendee@zuno.example',
        extensions.crypt('change-me-locally', extensions.gen_salt('bf')), now(),
        '{"provider":"email","providers":["email"]}'::jsonb, '{"display_name":"Nethmi Perera"}'::jsonb,
        now(), now(), '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('b0000000-0000-4000-8000-0000000000aa', 'b0000000-0000-4000-8000-0000000000aa', '{"sub":"b0000000-0000-4000-8000-0000000000aa","email":"dev.attendee@zuno.example","email_verified":true}'::jsonb, 'email', now(), now(), now())
on conflict (provider_id, provider) do nothing;

update public.profiles
   set display_name = 'Nethmi Perera', city = 'Colombo', district = 'Colombo',
       preferred_categories = array['technology', 'hackathons', 'art']::text[],
       identity_status = 'verified_unique', onboarding_completed_at = now()
 where id = 'b0000000-0000-4000-8000-0000000000aa';

-- -----------------------------------------------------------------------------
-- Categories, organizers, venues
-- (1 venue(s) shared across organizers in the JSON were copied per organizer)
-- -----------------------------------------------------------------------------
insert into public.categories (id, name, symbol_name, sort_order) values ('hackathons', 'Hackathons', 'laptopcomputer', 1)
on conflict (id) do update set name = excluded.name, symbol_name = excluded.symbol_name, sort_order = excluded.sort_order;
insert into public.categories (id, name, symbol_name, sort_order) values ('technology', 'Technology', 'cpu', 2)
on conflict (id) do update set name = excluded.name, symbol_name = excluded.symbol_name, sort_order = excluded.sort_order;
insert into public.categories (id, name, symbol_name, sort_order) values ('workshops', 'Workshops', 'hammer', 3)
on conflict (id) do update set name = excluded.name, symbol_name = excluded.symbol_name, sort_order = excluded.sort_order;
insert into public.categories (id, name, symbol_name, sort_order) values ('university', 'University', 'graduationcap', 4)
on conflict (id) do update set name = excluded.name, symbol_name = excluded.symbol_name, sort_order = excluded.sort_order;
insert into public.categories (id, name, symbol_name, sort_order) values ('art', 'Art', 'photo.artframe', 5)
on conflict (id) do update set name = excluded.name, symbol_name = excluded.symbol_name, sort_order = excluded.sort_order;
insert into public.categories (id, name, symbol_name, sort_order) values ('music', 'Music', 'music.note', 6)
on conflict (id) do update set name = excluded.name, symbol_name = excluded.symbol_name, sort_order = excluded.sort_order;
insert into public.categories (id, name, symbol_name, sort_order) values ('sports', 'Sports', 'figure.run', 7)
on conflict (id) do update set name = excluded.name, symbol_name = excluded.symbol_name, sort_order = excluded.sort_order;
insert into public.categories (id, name, symbol_name, sort_order) values ('culture', 'Culture', 'building.columns', 8)
on conflict (id) do update set name = excluded.name, symbol_name = excluded.symbol_name, sort_order = excluded.sort_order;
insert into public.categories (id, name, symbol_name, sort_order) values ('careers', 'Careers', 'briefcase', 9)
on conflict (id) do update set name = excluded.name, symbol_name = excluded.symbol_name, sort_order = excluded.sort_order;
insert into public.categories (id, name, symbol_name, sort_order) values ('community', 'Community', 'person.3', 10)
on conflict (id) do update set name = excluded.name, symbol_name = excluded.symbol_name, sort_order = excluded.sort_order;

insert into public.organizer_profiles (id, owner_id, name, slug, bio, contact_email, verification_status)
values ('6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e01', 'a0000000-0000-4000-8000-000000000001', 'Colombo Builders Collective', 'colombo-builders', 'A volunteer community running hackathons and build nights for Sri Lankan developers.', 'hello@builders.example', 'verified')
on conflict (id) do nothing;
insert into public.organizer_profiles (id, owner_id, name, slug, bio, contact_email, verification_status)
values ('6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e02', 'a0000000-0000-4000-8000-000000000002', 'Kandy Arts Guild', 'kandy-arts-guild', 'Artists and craftspeople keeping hill-country traditions alive through workshops and performances.', 'guild@kandyarts.example', 'verified')
on conflict (id) do nothing;
insert into public.organizer_profiles (id, owner_id, name, slug, bio, contact_email, verification_status)
values ('6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e03', 'a0000000-0000-4000-8000-000000000003', 'Island Sound Society', 'island-sound', 'Live music evenings across the island, from jazz to baila.', 'tickets@islandsound.example', 'verified')
on conflict (id) do nothing;
insert into public.organizer_profiles (id, owner_id, name, slug, bio, contact_email, verification_status)
values ('6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e04', 'a0000000-0000-4000-8000-000000000004', 'Lanka Open Source Circle', 'lanka-oss', 'Meetups, community days and mentoring for open-source contributors in Sri Lanka.', 'team@lankaoss.example', 'verified')
on conflict (id) do nothing;
insert into public.organizer_profiles (id, owner_id, name, slug, bio, contact_email, verification_status)
values ('6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e05', 'a0000000-0000-4000-8000-000000000005', 'Student Tech Societies Network', 'student-tech', 'A network of university tech societies organising workshops, careers fairs and build nights.', 'network@studenttech.example', 'verified')
on conflict (id) do nothing;

insert into public.venues (id, organizer_id, name, address_line, city, district, latitude, longitude)
values ('7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f01', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e01', 'Innovation Hall', 'Galle Road, Colombo 03', 'Colombo', 'Colombo', 6.9022, 79.853)
on conflict (id) do nothing;
insert into public.venues (id, organizer_id, name, address_line, city, district, latitude, longitude)
values ('7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f02', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e05', 'Engineering Faculty Auditorium', 'Katubedda', 'Moratuwa', 'Colombo', 6.7951, 79.9009)
on conflict (id) do nothing;
insert into public.venues (id, organizer_id, name, address_line, city, district, latitude, longitude)
values ('7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f03', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e02', 'Lakeside Pavilion', 'Sangaraja Mawatha', 'Kandy', 'Kandy', 7.2916, 80.6413)
on conflict (id) do nothing;
insert into public.venues (id, organizer_id, name, address_line, city, district, latitude, longitude)
values ('7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f04', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e02', 'Fort Ramparts Meeting Point', 'Church Street, Galle Fort', 'Galle', 'Galle', 6.027, 80.217)
on conflict (id) do nothing;
insert into public.venues (id, organizer_id, name, address_line, city, district, latitude, longitude)
values ('7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f05', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e04', 'Northern Tech Hub', 'Hospital Road', 'Jaffna', 'Jaffna', 9.6615, 80.0255)
on conflict (id) do nothing;
insert into public.venues (id, organizer_id, name, address_line, city, district, latitude, longitude)
values ('7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f06', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e03', 'Garden Amphitheatre', 'Independence Avenue, Colombo 07', 'Colombo', 'Colombo', 6.9046, 79.8686)
on conflict (id) do nothing;
insert into public.venues (id, organizer_id, name, address_line, city, district, latitude, longitude)
values ('7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f07', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e05', 'Main Hall, Faculty of Science', 'Cumaratunga Munidasa Mawatha, Colombo 03', 'Colombo', 'Colombo', 6.9006, 79.8607)
on conflict (id) do nothing;
insert into public.venues (id, organizer_id, name, address_line, city, district, latitude, longitude)
values ('7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f08', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e02', 'Community Arts Studio', 'Marine Drive, Wellawatte', 'Colombo', 'Colombo', 6.8741, 79.859)
on conflict (id) do nothing;
insert into public.venues (id, organizer_id, name, address_line, city, district, latitude, longitude)
values ('7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f09', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e03', 'Beach Park Start Line', 'Lewis Place', 'Negombo', 'Gampaha', 7.218, 79.8399)
on conflict (id) do nothing;
insert into public.venues (id, organizer_id, name, address_line, city, district, latitude, longitude)
values ('7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f10', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e05', 'Engineering Workshop Lab', 'Peradeniya', 'Kandy', 'Kandy', 7.2549, 80.5917)
on conflict (id) do nothing;
insert into public.venues (id, organizer_id, name, address_line, city, district, latitude, longitude)
values ('7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f11', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e02', 'Old Town Gallery', 'Horton Place, Colombo 07', 'Colombo', 'Colombo', 6.9113, 79.8701)
on conflict (id) do nothing;
insert into public.venues (id, organizer_id, name, address_line, city, district, latitude, longitude)
values ('7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f12', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e03', 'Lagoon Front Stage', 'Bar Road', 'Batticaloa', 'Batticaloa', 7.731, 81.6747)
on conflict (id) do nothing;
insert into public.venues (id, organizer_id, name, address_line, city, district, latitude, longitude)
values ('7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f13', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e01', 'Sports Complex Nets', 'Reid Avenue, Colombo 07', 'Colombo', 'Colombo', 6.9008, 79.8652)
on conflict (id) do nothing;
insert into public.venues (id, organizer_id, name, address_line, city, district, latitude, longitude)
values ('278a313e-c607-56f3-84e3-f78a40c2c619', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e04', 'Innovation Hall', 'Galle Road, Colombo 03', 'Colombo', 'Colombo', 6.9022, 79.853)
on conflict (id) do nothing;

-- -----------------------------------------------------------------------------
-- Events (published; events that already ended are seeded as 'completed').
-- Paid events: seats_taken = sum of tier `sold` (the JSON's seats_taken is 0).
-- Online/hybrid events get a placeholder https://live.zuno.example/<slug> link.
-- -----------------------------------------------------------------------------
insert into public.events (id, organizer_id, category_id, venue_id, title, summary, description, format,
                           starts_at, ends_at, capacity, is_free, university, tags, cover_path, cover_alt,
                           agenda, speakers, refund_policy, online_url, status, seats_taken,
                           creation_fee_paid_at, published_at)
select 'e1000000-0000-4000-8000-000000000001', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e01', 'hackathons', '7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f01', 'Climate AI Hackathon', 'Thirty-six hours to build tools for flood and heat resilience', 'Teams of up to four build working prototypes that help Sri Lankan communities prepare for floods, landslides and extreme heat. Mentors from climate research, civic tech and design join throughout the weekend. Meals, Wi-Fi and sleeping space are provided. Bring a laptop, a charger and an open mind.', 'physical',
       s.starts_at, s.starts_at + make_interval(secs => 129600), 240, true, null, array['ai', 'climate', 'python', 'civic tech']::text[], 'seed/climate-ai-hackathon.jpg', 'Abstract painting of rain clouds over green terraces in deep teal and amber',
       pg_temp.seed_agenda(s.starts_at, '[{"offset_hours":0,"duration_hours":1,"title":"Check-in and breakfast","detail":"Collect your badge at the main entrance."},{"offset_hours":1,"duration_hours":1,"title":"Problem statements","detail":"Briefings from climate researchers."},{"offset_hours":2,"duration_hours":30,"title":"Build sprint","detail":"Mentor office hours every three hours."},{"offset_hours":33,"duration_hours":3,"title":"Demos and awards","detail":"Three-minute demos for each team."}]'::jsonb), '[{"name":"Dr. Ishara Gunawardena","role":"Climate data scientist","organization":"Sample Research Lab"},{"name":"Ravindu Jayasinghe","role":"Civic tech lead","organization":"Colombo Builders Collective"}]'::jsonb, 'Free registration. Please cancel at least 24 hours before the start so your seat can go to someone on the waitlist.', null,
       case when s.starts_at + make_interval(secs => 129600) <= now() then 'completed' else 'published' end, 168,
       now() - interval '21 days', now() - interval '14 days'
  from (select pg_temp.seed_at(5, '08:30') as starts_at) s
on conflict (id) do nothing;
insert into public.event_media (event_id, storage_path, kind, alt_text, sort_order)
select 'e1000000-0000-4000-8000-000000000001', 'seed/climate-ai-hackathon.jpg', 'cover', 'Abstract painting of rain clouds over green terraces in deep teal and amber', 0
 where not exists (select 1 from public.event_media where event_id = 'e1000000-0000-4000-8000-000000000001' and kind = 'cover');
insert into public.registration_questions (id, event_id, prompt, kind, options, required, sort_order)
values ('4348cac3-2824-5701-8d12-e6fa95140eff', 'e1000000-0000-4000-8000-000000000001', 'Team name (optional)', 'short_text', '[]'::jsonb, false, 0)
on conflict (id) do nothing;
insert into public.registration_questions (id, event_id, prompt, kind, options, required, sort_order)
values ('d9d358bb-3e71-568e-a180-afe535e300d1', 'e1000000-0000-4000-8000-000000000001', 'Primary skill', 'single_choice', '["Software","Data","Design","Hardware","Domain expert"]'::jsonb, true, 1)
on conflict (id) do nothing;
insert into public.registration_questions (id, event_id, prompt, kind, options, required, sort_order)
values ('c354e419-4863-5162-90ea-f8171db1b667', 'e1000000-0000-4000-8000-000000000001', 'Do you need overnight accommodation?', 'yes_no', '[]'::jsonb, true, 2)
on conflict (id) do nothing;

insert into public.events (id, organizer_id, category_id, venue_id, title, summary, description, format,
                           starts_at, ends_at, capacity, is_free, university, tags, cover_path, cover_alt,
                           agenda, speakers, refund_policy, online_url, status, seats_taken,
                           creation_fee_paid_at, published_at)
select 'e1000000-0000-4000-8000-000000000002', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e05', 'workshops', '7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f02', 'Native iOS with SwiftUI', 'A hands-on afternoon building your first native iPhone app', 'Learn layout, state and navigation in SwiftUI by building a small event browser from scratch. Suitable for students who know any programming language. Mac laptops are shared in pairs; bring your own if you have one.', 'physical',
       s.starts_at, s.starts_at + make_interval(secs => 10800), 60, true, 'University of Moratuwa', array['swift', 'ios', 'mobile', 'students']::text[], 'seed/swiftui-workshop.jpg', 'Painting of a glowing laptop on a wooden desk beside a window at dusk',
       pg_temp.seed_agenda(s.starts_at, '[{"offset_hours":0,"duration_hours":1,"title":"SwiftUI fundamentals","detail":"Views, modifiers and state."},{"offset_hours":1,"duration_hours":1.5,"title":"Build along","detail":"Lists, navigation and data."},{"offset_hours":2.5,"duration_hours":0.5,"title":"Show and tell","detail":""}]'::jsonb), '[{"name":"Tharushi Wickramasinghe","role":"iOS engineer","organization":"Student Tech Societies Network"}]'::jsonb, 'Free registration. Cancel any time before the workshop starts.', null,
       case when s.starts_at + make_interval(secs => 10800) <= now() then 'completed' else 'published' end, 41,
       now() - interval '21 days', now() - interval '14 days'
  from (select pg_temp.seed_at(2, '14:00') as starts_at) s
on conflict (id) do nothing;
insert into public.event_media (event_id, storage_path, kind, alt_text, sort_order)
select 'e1000000-0000-4000-8000-000000000002', 'seed/swiftui-workshop.jpg', 'cover', 'Painting of a glowing laptop on a wooden desk beside a window at dusk', 0
 where not exists (select 1 from public.event_media where event_id = 'e1000000-0000-4000-8000-000000000002' and kind = 'cover');
insert into public.registration_questions (id, event_id, prompt, kind, options, required, sort_order)
values ('20d69f82-756b-5729-9606-1403d1a582b1', 'e1000000-0000-4000-8000-000000000002', 'Will you bring your own Mac?', 'yes_no', '[]'::jsonb, true, 0)
on conflict (id) do nothing;

insert into public.events (id, organizer_id, category_id, venue_id, title, summary, description, format,
                           starts_at, ends_at, capacity, is_free, university, tags, cover_path, cover_alt,
                           agenda, speakers, refund_policy, online_url, status, seats_taken,
                           creation_fee_paid_at, published_at)
select 'e1000000-0000-4000-8000-000000000003', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e02', 'culture', '7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f03', 'Kandyan Drumming Circle', 'An evening of geta bera rhythms by the lake', 'Master drummers introduce the rhythms that accompany Kandyan dance, then invite the audience to learn a simple pattern together. The evening closes with a full ensemble performance as the lake lights come on.', 'physical',
       s.starts_at, s.starts_at + make_interval(secs => 9000), 180, false, null, array['drumming', 'kandy', 'heritage', 'performance']::text[], 'seed/kandyan-drumming.jpg', 'Oil-style painting of drums glowing in warm lamplight beside a dark lake',
       pg_temp.seed_agenda(s.starts_at, '[{"offset_hours":0,"duration_hours":0.5,"title":"Welcome","detail":""},{"offset_hours":0.5,"duration_hours":1,"title":"Learn a rhythm","detail":"Drums provided."},{"offset_hours":1.5,"duration_hours":1,"title":"Ensemble performance","detail":""}]'::jsonb), '[{"name":"Gunadasa Herath","role":"Master drummer","organization":"Kandy Arts Guild"}]'::jsonb, 'Full refund as wallet credit up to 48 hours before the event. No refunds after that.', null,
       case when s.starts_at + make_interval(secs => 9000) <= now() then 'completed' else 'published' end, 89,
       now() - interval '21 days', now() - interval '14 days'
  from (select pg_temp.seed_at(9, '17:30') as starts_at) s
on conflict (id) do nothing;
insert into public.event_media (event_id, storage_path, kind, alt_text, sort_order)
select 'e1000000-0000-4000-8000-000000000003', 'seed/kandyan-drumming.jpg', 'cover', 'Oil-style painting of drums glowing in warm lamplight beside a dark lake', 0
 where not exists (select 1 from public.event_media where event_id = 'e1000000-0000-4000-8000-000000000003' and kind = 'cover');
insert into public.ticket_tiers (id, event_id, name, description, price_minor, currency, quantity,
                                 max_per_order, sort_order, sold)
values ('f1000000-0000-4000-8000-000000000031', 'e1000000-0000-4000-8000-000000000003', 'Standard', 'Lakeside seating', 150000, 'LKR', 150, 6, 0, 62)
on conflict (id) do nothing;
insert into public.ticket_tiers (id, event_id, name, description, price_minor, currency, quantity,
                                 max_per_order, sort_order, sold)
values ('f1000000-0000-4000-8000-000000000032', 'e1000000-0000-4000-8000-000000000003', 'Front row', 'First two rows with a drum to try', 250000, 'LKR', 30, 2, 1, 27)
on conflict (id) do nothing;
insert into public.event_settlements (event_id) values ('e1000000-0000-4000-8000-000000000003') on conflict (event_id) do nothing;

insert into public.events (id, organizer_id, category_id, venue_id, title, summary, description, format,
                           starts_at, ends_at, capacity, is_free, university, tags, cover_path, cover_alt,
                           agenda, speakers, refund_policy, online_url, status, seats_taken,
                           creation_fee_paid_at, published_at)
select 'e1000000-0000-4000-8000-000000000004', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e02', 'art', '7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f04', 'Golden Hour in Galle Fort', 'A guided photo walk along the ramparts at sunset', 'Walk the ramparts with a documentary photographer and learn to work with low, warm light, long shadows and colonial architecture. Any camera or phone is welcome. Limited to a small group so everyone gets feedback.', 'physical',
       s.starts_at, s.starts_at + make_interval(secs => 7200), 25, true, null, array['photography', 'galle', 'walk', 'sunset']::text[], 'seed/galle-photo-walk.jpg', 'Painting of a lighthouse and fort walls bathed in orange sunset light',
       pg_temp.seed_agenda(s.starts_at, '[{"offset_hours":0,"duration_hours":0.5,"title":"Meet at the clock tower","detail":""},{"offset_hours":0.5,"duration_hours":1.5,"title":"Rampart walk","detail":""}]'::jsonb), '[{"name":"Shanika de Silva","role":"Documentary photographer","organization":"Kandy Arts Guild"}]'::jsonb, 'Free registration. Please cancel if you cannot attend; the group is small.', null,
       case when s.starts_at + make_interval(secs => 7200) <= now() then 'completed' else 'published' end, 22,
       now() - interval '21 days', now() - interval '14 days'
  from (select pg_temp.seed_at(3, '16:30') as starts_at) s
on conflict (id) do nothing;
insert into public.event_media (event_id, storage_path, kind, alt_text, sort_order)
select 'e1000000-0000-4000-8000-000000000004', 'seed/galle-photo-walk.jpg', 'cover', 'Painting of a lighthouse and fort walls bathed in orange sunset light', 0
 where not exists (select 1 from public.event_media where event_id = 'e1000000-0000-4000-8000-000000000004' and kind = 'cover');
insert into public.registration_questions (id, event_id, prompt, kind, options, required, sort_order)
values ('8dd5c2c6-2bde-5ef1-bf3f-2bbb0486d02c', 'e1000000-0000-4000-8000-000000000004', 'What will you shoot with?', 'single_choice', '["Phone","Mirrorless","DSLR","Film"]'::jsonb, false, 0)
on conflict (id) do nothing;

insert into public.events (id, organizer_id, category_id, venue_id, title, summary, description, format,
                           starts_at, ends_at, capacity, is_free, university, tags, cover_path, cover_alt,
                           agenda, speakers, refund_policy, online_url, status, seats_taken,
                           creation_fee_paid_at, published_at)
select 'e1000000-0000-4000-8000-000000000005', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e04', 'technology', '7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f05', 'Northern Tech Meetup', 'Cloud, data and the startups growing in the North', 'Three short talks on running data platforms on a budget, followed by an open discussion with founders building from Jaffna. Talks are in English and Tamil.', 'physical',
       s.starts_at, s.starts_at + make_interval(secs => 10800), 120, true, 'University of Jaffna', array['cloud', 'data', 'startups', 'tamil']::text[], 'seed/jaffna-tech-meetup.jpg', 'Painting of palmyra palms against a violet evening sky',
       pg_temp.seed_agenda(s.starts_at, '[{"offset_hours":0,"duration_hours":1.5,"title":"Lightning talks","detail":""},{"offset_hours":1.5,"duration_hours":1.5,"title":"Founder discussion","detail":""}]'::jsonb), '[{"name":"Kavitha Sivakumar","role":"Data engineer","organization":"Lanka Open Source Circle"}]'::jsonb, 'Free registration.', null,
       case when s.starts_at + make_interval(secs => 10800) <= now() then 'completed' else 'published' end, 37,
       now() - interval '21 days', now() - interval '14 days'
  from (select pg_temp.seed_at(12, '17:00') as starts_at) s
on conflict (id) do nothing;
insert into public.event_media (event_id, storage_path, kind, alt_text, sort_order)
select 'e1000000-0000-4000-8000-000000000005', 'seed/jaffna-tech-meetup.jpg', 'cover', 'Painting of palmyra palms against a violet evening sky', 0
 where not exists (select 1 from public.event_media where event_id = 'e1000000-0000-4000-8000-000000000005' and kind = 'cover');

insert into public.events (id, organizer_id, category_id, venue_id, title, summary, description, format,
                           starts_at, ends_at, capacity, is_free, university, tags, cover_path, cover_alt,
                           agenda, speakers, refund_policy, online_url, status, seats_taken,
                           creation_fee_paid_at, published_at)
select 'e1000000-0000-4000-8000-000000000006', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e03', 'music', '7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f06', 'Jazz Under the Stars', 'An open-air evening of jazz standards and island grooves', 'A quartet and guest vocalists perform jazz standards alongside reimagined Sri Lankan classics in the garden amphitheatre. Food stalls open an hour before the first set.', 'physical',
       s.starts_at, s.starts_at + make_interval(secs => 10800), 400, false, null, array['jazz', 'live music', 'outdoor']::text[], 'seed/jazz-under-the-stars.jpg', 'Painting of a saxophone silhouetted against a night sky with string lights',
       pg_temp.seed_agenda(s.starts_at, '[{"offset_hours":0,"duration_hours":1.25,"title":"First set","detail":""},{"offset_hours":1.25,"duration_hours":0.5,"title":"Interval","detail":""},{"offset_hours":1.75,"duration_hours":1.25,"title":"Second set","detail":""}]'::jsonb), '[]'::jsonb, 'Wallet-credit refunds up to 72 hours before the show.', null,
       case when s.starts_at + make_interval(secs => 10800) <= now() then 'completed' else 'published' end, 259,
       now() - interval '21 days', now() - interval '14 days'
  from (select pg_temp.seed_at(6, '19:30') as starts_at) s
on conflict (id) do nothing;
insert into public.event_media (event_id, storage_path, kind, alt_text, sort_order)
select 'e1000000-0000-4000-8000-000000000006', 'seed/jazz-under-the-stars.jpg', 'cover', 'Painting of a saxophone silhouetted against a night sky with string lights', 0
 where not exists (select 1 from public.event_media where event_id = 'e1000000-0000-4000-8000-000000000006' and kind = 'cover');
insert into public.ticket_tiers (id, event_id, name, description, price_minor, currency, quantity,
                                 max_per_order, sort_order, sold)
values ('f1000000-0000-4000-8000-000000000061', 'e1000000-0000-4000-8000-000000000006', 'Lawn', 'Bring a mat', 300000, 'LKR', 300, 6, 0, 188)
on conflict (id) do nothing;
insert into public.ticket_tiers (id, event_id, name, description, price_minor, currency, quantity,
                                 max_per_order, sort_order, sold)
values ('f1000000-0000-4000-8000-000000000062', 'e1000000-0000-4000-8000-000000000006', 'Reserved seating', 'Numbered chairs near the stage', 500000, 'LKR', 100, 4, 1, 71)
on conflict (id) do nothing;
insert into public.event_settlements (event_id) values ('e1000000-0000-4000-8000-000000000006') on conflict (event_id) do nothing;

insert into public.events (id, organizer_id, category_id, venue_id, title, summary, description, format,
                           starts_at, ends_at, capacity, is_free, university, tags, cover_path, cover_alt,
                           agenda, speakers, refund_policy, online_url, status, seats_taken,
                           creation_fee_paid_at, published_at)
select 'e1000000-0000-4000-8000-000000000007', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e05', 'careers', '7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f07', 'Tech Careers Fair', 'Meet forty employers hiring interns and graduates', 'Bring your CV and meet engineering, product and data teams hiring for internships and graduate roles. Free CV clinics run all day, and a panel covers how to prepare for technical interviews.', 'physical',
       s.starts_at, s.starts_at + make_interval(secs => 25200), 800, true, 'University of Colombo', array['careers', 'internships', 'cv']::text[], 'seed/tech-careers-fair.jpg', 'Painting of a sunlit hall with tall arched windows',
       pg_temp.seed_agenda(s.starts_at, '[{"offset_hours":0,"duration_hours":7,"title":"Employer booths","detail":""},{"offset_hours":3,"duration_hours":1,"title":"Interview panel","detail":""}]'::jsonb), '[]'::jsonb, 'Free registration.', null,
       case when s.starts_at + make_interval(secs => 25200) <= now() then 'completed' else 'published' end, 512,
       now() - interval '21 days', now() - interval '14 days'
  from (select pg_temp.seed_at(15, '09:00') as starts_at) s
on conflict (id) do nothing;
insert into public.event_media (event_id, storage_path, kind, alt_text, sort_order)
select 'e1000000-0000-4000-8000-000000000007', 'seed/tech-careers-fair.jpg', 'cover', 'Painting of a sunlit hall with tall arched windows', 0
 where not exists (select 1 from public.event_media where event_id = 'e1000000-0000-4000-8000-000000000007' and kind = 'cover');
insert into public.registration_questions (id, event_id, prompt, kind, options, required, sort_order)
values ('32052ba0-aba3-5d20-976a-5c00fae57ca6', 'e1000000-0000-4000-8000-000000000007', 'Year of study', 'single_choice', '["1st year","2nd year","3rd year","4th year","Graduate"]'::jsonb, true, 0)
on conflict (id) do nothing;
insert into public.registration_questions (id, event_id, prompt, kind, options, required, sort_order)
values ('facb7922-1961-576d-8db7-6ab8527d3ce0', 'e1000000-0000-4000-8000-000000000007', 'Areas of interest', 'multi_choice', '["Software","Data","Product","Design","Hardware"]'::jsonb, false, 1)
on conflict (id) do nothing;

insert into public.events (id, organizer_id, category_id, venue_id, title, summary, description, format,
                           starts_at, ends_at, capacity, is_free, university, tags, cover_path, cover_alt,
                           agenda, speakers, refund_policy, online_url, status, seats_taken,
                           creation_fee_paid_at, published_at)
select 'e1000000-0000-4000-8000-000000000008', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e02', 'culture', '7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f08', 'Kolam & Clay Lamp Workshop', 'Create festival kolam patterns and paint your own clay lamps', 'Ahead of the festival season, learn the geometry behind traditional kolam patterns and decorate a set of clay lamps to take home. All materials are included in the ticket.', 'physical',
       s.starts_at, s.starts_at + make_interval(secs => 10800), 40, false, null, array['kolam', 'craft', 'festival', 'family']::text[], 'seed/kolam-lamp-workshop.jpg', 'Painting of small clay lamps glowing over a colourful floor pattern',
       pg_temp.seed_agenda(s.starts_at, '[{"offset_hours":0,"duration_hours":1.5,"title":"Kolam patterns","detail":""},{"offset_hours":1.5,"duration_hours":1.5,"title":"Lamp painting","detail":""}]'::jsonb), '[{"name":"Meena Rajaratnam","role":"Craft teacher","organization":"Kandy Arts Guild"}]'::jsonb, 'Wallet-credit refund up to 24 hours before the workshop.', null,
       case when s.starts_at + make_interval(secs => 10800) <= now() then 'completed' else 'published' end, 14,
       now() - interval '21 days', now() - interval '14 days'
  from (select pg_temp.seed_at(20, '10:00') as starts_at) s
on conflict (id) do nothing;
insert into public.event_media (event_id, storage_path, kind, alt_text, sort_order)
select 'e1000000-0000-4000-8000-000000000008', 'seed/kolam-lamp-workshop.jpg', 'cover', 'Painting of small clay lamps glowing over a colourful floor pattern', 0
 where not exists (select 1 from public.event_media where event_id = 'e1000000-0000-4000-8000-000000000008' and kind = 'cover');
insert into public.ticket_tiers (id, event_id, name, description, price_minor, currency, quantity,
                                 max_per_order, sort_order, sold)
values ('f1000000-0000-4000-8000-000000000081', 'e1000000-0000-4000-8000-000000000008', 'Workshop place', 'Includes all materials', 100000, 'LKR', 40, 4, 0, 14)
on conflict (id) do nothing;
insert into public.registration_questions (id, event_id, prompt, kind, options, required, sort_order)
values ('e584af99-8fc4-591f-ba53-af20cac5f24b', 'e1000000-0000-4000-8000-000000000008', 'Any accessibility needs we should prepare for?', 'long_text', '[]'::jsonb, false, 0)
on conflict (id) do nothing;
insert into public.event_settlements (event_id) values ('e1000000-0000-4000-8000-000000000008') on conflict (event_id) do nothing;

insert into public.events (id, organizer_id, category_id, venue_id, title, summary, description, format,
                           starts_at, ends_at, capacity, is_free, university, tags, cover_path, cover_alt,
                           agenda, speakers, refund_policy, online_url, status, seats_taken,
                           creation_fee_paid_at, published_at)
select 'e1000000-0000-4000-8000-000000000009', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e03', 'sports', '7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f09', 'Negombo Sunrise 10K', 'A flat coastal run that finishes on the beach', 'Run or walk 10 kilometres along the coast as the sun comes up. Timing chips, a finisher medal and breakfast are included. Pacers run at 50, 60 and 70 minutes.', 'physical',
       s.starts_at, s.starts_at + make_interval(secs => 10800), 300, false, null, array['running', '10k', 'beach']::text[], 'seed/negombo-sunrise-10k.jpg', 'Painting of a pale sunrise over calm sea and fishing boats',
       pg_temp.seed_agenda(s.starts_at, '[{"offset_hours":0,"duration_hours":0.5,"title":"Warm-up","detail":""},{"offset_hours":0.5,"duration_hours":1.5,"title":"Race","detail":""},{"offset_hours":2,"duration_hours":1,"title":"Breakfast and medals","detail":""}]'::jsonb), '[]'::jsonb, 'No refunds; transfers allowed until race week.', null,
       case when s.starts_at + make_interval(secs => 10800) <= now() then 'completed' else 'published' end, 300,
       now() - interval '21 days', now() - interval '14 days'
  from (select pg_temp.seed_at(14, '05:45') as starts_at) s
on conflict (id) do nothing;
insert into public.event_media (event_id, storage_path, kind, alt_text, sort_order)
select 'e1000000-0000-4000-8000-000000000009', 'seed/negombo-sunrise-10k.jpg', 'cover', 'Painting of a pale sunrise over calm sea and fishing boats', 0
 where not exists (select 1 from public.event_media where event_id = 'e1000000-0000-4000-8000-000000000009' and kind = 'cover');
insert into public.ticket_tiers (id, event_id, name, description, price_minor, currency, quantity,
                                 max_per_order, sort_order, sold)
values ('f1000000-0000-4000-8000-000000000091', 'e1000000-0000-4000-8000-000000000009', 'Race entry', 'Chip timing, medal and breakfast', 200000, 'LKR', 300, 2, 0, 300)
on conflict (id) do nothing;
insert into public.registration_questions (id, event_id, prompt, kind, options, required, sort_order)
values ('deeddf08-8cdc-5784-82d2-b0a7e1621834', 'e1000000-0000-4000-8000-000000000009', 'T-shirt size', 'single_choice', '["XS","S","M","L","XL"]'::jsonb, true, 0)
on conflict (id) do nothing;
insert into public.event_settlements (event_id) values ('e1000000-0000-4000-8000-000000000009') on conflict (event_id) do nothing;

insert into public.events (id, organizer_id, category_id, venue_id, title, summary, description, format,
                           starts_at, ends_at, capacity, is_free, university, tags, cover_path, cover_alt,
                           agenda, speakers, refund_policy, online_url, status, seats_taken,
                           creation_fee_paid_at, published_at)
select 'e1000000-0000-4000-8000-000000000010', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e05', 'university', '7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f10', 'Robotics Build Night', 'Build a line-following robot in one evening', 'Work in pairs to assemble and program a small line-following robot. Kits and soldering stations are provided by the engineering society. No prior hardware experience needed.', 'physical',
       s.starts_at, s.starts_at + make_interval(secs => 14400), 40, true, 'University of Peradeniya', array['robotics', 'hardware', 'arduino']::text[], 'seed/robotics-build-night.jpg', 'Painting of copper circuitry glowing like a city at night',
       pg_temp.seed_agenda(s.starts_at, '[{"offset_hours":0,"duration_hours":1,"title":"Kit walkthrough","detail":""},{"offset_hours":1,"duration_hours":3,"title":"Build and race","detail":""}]'::jsonb), '[]'::jsonb, 'Free registration.', null,
       case when s.starts_at + make_interval(secs => 14400) <= now() then 'completed' else 'published' end, 31,
       now() - interval '21 days', now() - interval '14 days'
  from (select pg_temp.seed_at(8, '18:00') as starts_at) s
on conflict (id) do nothing;
insert into public.event_media (event_id, storage_path, kind, alt_text, sort_order)
select 'e1000000-0000-4000-8000-000000000010', 'seed/robotics-build-night.jpg', 'cover', 'Painting of copper circuitry glowing like a city at night', 0
 where not exists (select 1 from public.event_media where event_id = 'e1000000-0000-4000-8000-000000000010' and kind = 'cover');
insert into public.registration_questions (id, event_id, prompt, kind, options, required, sort_order)
values ('61611dca-e60f-5812-bf1d-705e4e2f3ccf', 'e1000000-0000-4000-8000-000000000010', 'Faculty', 'short_text', '[]'::jsonb, true, 0)
on conflict (id) do nothing;

insert into public.events (id, organizer_id, category_id, venue_id, title, summary, description, format,
                           starts_at, ends_at, capacity, is_free, university, tags, cover_path, cover_alt,
                           agenda, speakers, refund_policy, online_url, status, seats_taken,
                           creation_fee_paid_at, published_at)
select 'e1000000-0000-4000-8000-000000000011', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e02', 'art', '7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f11', 'Island Light', 'Contemporary painters on the colour of the coast and hills', 'An exhibition of new paintings by twelve Sri Lankan artists exploring how light changes from the southern coast to the central hills. Free entry daily; guided tours run every Saturday morning.', 'physical',
       s.starts_at, s.starts_at + make_interval(secs => 2851200), 2000, true, null, array['painting', 'exhibition', 'contemporary']::text[], 'seed/island-light-exhibition.jpg', 'Painting of misty tea-covered hills under soft morning light',
       pg_temp.seed_agenda(s.starts_at, '[]'::jsonb), '[]'::jsonb, 'Free entry.', null,
       case when s.starts_at + make_interval(secs => 2851200) <= now() then 'completed' else 'published' end, 640,
       now() - interval '21 days', now() - interval '14 days'
  from (select pg_temp.seed_at(-2, '10:00') as starts_at) s
on conflict (id) do nothing;
insert into public.event_media (event_id, storage_path, kind, alt_text, sort_order)
select 'e1000000-0000-4000-8000-000000000011', 'seed/island-light-exhibition.jpg', 'cover', 'Painting of misty tea-covered hills under soft morning light', 0
 where not exists (select 1 from public.event_media where event_id = 'e1000000-0000-4000-8000-000000000011' and kind = 'cover');

insert into public.events (id, organizer_id, category_id, venue_id, title, summary, description, format,
                           starts_at, ends_at, capacity, is_free, university, tags, cover_path, cover_alt,
                           agenda, speakers, refund_policy, online_url, status, seats_taken,
                           creation_fee_paid_at, published_at)
select 'e1000000-0000-4000-8000-000000000012', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e04', 'community', '278a313e-c607-56f3-84e3-f78a40c2c619', 'Open Source Community Day', 'Your first pull request, with mentors beside you', 'Maintainers of local and global projects pair with first-time contributors. Pick an issue, get it reviewed and merged before the day ends. Join in person or follow the stream online.', 'hybrid',
       s.starts_at, s.starts_at + make_interval(secs => 25200), 150, true, null, array['open source', 'git', 'mentoring']::text[], 'seed/open-source-day.jpg', 'Painting of many lanterns joined by threads of light',
       pg_temp.seed_agenda(s.starts_at, '[{"offset_hours":0,"duration_hours":1,"title":"Choosing an issue","detail":""},{"offset_hours":1,"duration_hours":5,"title":"Mentored contribution","detail":""},{"offset_hours":6,"duration_hours":1,"title":"Merged!","detail":""}]'::jsonb), '[{"name":"Nimal Fernando","role":"Maintainer","organization":"Lanka Open Source Circle"}]'::jsonb, 'Free registration.', 'https://live.zuno.example/open-source-day',
       case when s.starts_at + make_interval(secs => 25200) <= now() then 'completed' else 'published' end, 98,
       now() - interval '21 days', now() - interval '14 days'
  from (select pg_temp.seed_at(4, '09:30') as starts_at) s
on conflict (id) do nothing;
insert into public.event_media (event_id, storage_path, kind, alt_text, sort_order)
select 'e1000000-0000-4000-8000-000000000012', 'seed/open-source-day.jpg', 'cover', 'Painting of many lanterns joined by threads of light', 0
 where not exists (select 1 from public.event_media where event_id = 'e1000000-0000-4000-8000-000000000012' and kind = 'cover');
insert into public.registration_questions (id, event_id, prompt, kind, options, required, sort_order)
values ('ed7f6482-bfe1-56b5-898e-4c2175b593ef', 'e1000000-0000-4000-8000-000000000012', 'GitHub username', 'short_text', '[]'::jsonb, false, 0)
on conflict (id) do nothing;

insert into public.events (id, organizer_id, category_id, venue_id, title, summary, description, format,
                           starts_at, ends_at, capacity, is_free, university, tags, cover_path, cover_alt,
                           agenda, speakers, refund_policy, online_url, status, seats_taken,
                           creation_fee_paid_at, published_at)
select 'e1000000-0000-4000-8000-000000000013', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e04', 'technology', null, 'Design Systems in Practice', 'An online evening on tokens, components and accessibility', 'Designers and engineers from Sri Lankan product teams share how they built and maintain their design systems, with a focus on accessibility and localisation for Sinhala and Tamil.', 'online',
       s.starts_at, s.starts_at + make_interval(secs => 7200), 500, true, null, array['design', 'accessibility', 'localisation']::text[], 'seed/design-systems-online.jpg', 'Painting of overlapping translucent coloured panes',
       pg_temp.seed_agenda(s.starts_at, '[{"offset_hours":0,"duration_hours":1.5,"title":"Talks","detail":""},{"offset_hours":1.5,"duration_hours":0.5,"title":"Q&A","detail":""}]'::jsonb), '[{"name":"Sachini Abeysekara","role":"Design lead","organization":"Lanka Open Source Circle"}]'::jsonb, 'Free registration.', 'https://live.zuno.example/design-systems-online',
       case when s.starts_at + make_interval(secs => 7200) <= now() then 'completed' else 'published' end, 211,
       now() - interval '21 days', now() - interval '14 days'
  from (select pg_temp.seed_at(7, '19:00') as starts_at) s
on conflict (id) do nothing;
insert into public.event_media (event_id, storage_path, kind, alt_text, sort_order)
select 'e1000000-0000-4000-8000-000000000013', 'seed/design-systems-online.jpg', 'cover', 'Painting of overlapping translucent coloured panes', 0
 where not exists (select 1 from public.event_media where event_id = 'e1000000-0000-4000-8000-000000000013' and kind = 'cover');

insert into public.events (id, organizer_id, category_id, venue_id, title, summary, description, format,
                           starts_at, ends_at, capacity, is_free, university, tags, cover_path, cover_alt,
                           agenda, speakers, refund_policy, online_url, status, seats_taken,
                           creation_fee_paid_at, published_at)
select 'e1000000-0000-4000-8000-000000000014', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e01', 'sports', '7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f13', 'Junior Cricket Clinic', 'Batting and bowling basics for ages 10 to 15', 'Qualified coaches run a morning of batting, bowling and fielding drills in small groups. Equipment provided; bring water and a cap.', 'physical',
       s.starts_at, s.starts_at + make_interval(secs => 14400), 60, false, null, array['cricket', 'kids', 'coaching']::text[], 'seed/junior-cricket-clinic.jpg', 'Painting of a cricket ground at morning with long shadows',
       pg_temp.seed_agenda(s.starts_at, '[]'::jsonb), '[]'::jsonb, 'Wallet-credit refund up to 48 hours before.', null,
       case when s.starts_at + make_interval(secs => 14400) <= now() then 'completed' else 'published' end, 22,
       now() - interval '21 days', now() - interval '14 days'
  from (select pg_temp.seed_at(10, '08:00') as starts_at) s
on conflict (id) do nothing;
insert into public.event_media (event_id, storage_path, kind, alt_text, sort_order)
select 'e1000000-0000-4000-8000-000000000014', 'seed/junior-cricket-clinic.jpg', 'cover', 'Painting of a cricket ground at morning with long shadows', 0
 where not exists (select 1 from public.event_media where event_id = 'e1000000-0000-4000-8000-000000000014' and kind = 'cover');
insert into public.ticket_tiers (id, event_id, name, description, price_minor, currency, quantity,
                                 max_per_order, sort_order, sold)
values ('f1000000-0000-4000-8000-000000000141', 'e1000000-0000-4000-8000-000000000014', 'Participant', 'One child', 120000, 'LKR', 60, 3, 0, 22)
on conflict (id) do nothing;
insert into public.registration_questions (id, event_id, prompt, kind, options, required, sort_order)
values ('0a4edd38-f934-5665-9746-ca4be7eb9677', 'e1000000-0000-4000-8000-000000000014', 'Participant age', 'short_text', '[]'::jsonb, true, 0)
on conflict (id) do nothing;
insert into public.event_settlements (event_id) values ('e1000000-0000-4000-8000-000000000014') on conflict (event_id) do nothing;

insert into public.events (id, organizer_id, category_id, venue_id, title, summary, description, format,
                           starts_at, ends_at, capacity, is_free, university, tags, cover_path, cover_alt,
                           agenda, speakers, refund_policy, online_url, status, seats_taken,
                           creation_fee_paid_at, published_at)
select 'e1000000-0000-4000-8000-000000000015', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e04', 'careers', '278a313e-c607-56f3-84e3-f78a40c2c619', 'Startup Pitch Night', 'Eight early-stage founders, five minutes each', 'Founders pitch to a panel of angel investors and operators, followed by open networking. Audience votes for the community prize.', 'physical',
       s.starts_at, s.starts_at + make_interval(secs => 10800), 200, false, null, array['startups', 'pitch', 'networking']::text[], 'seed/startup-pitch-night.jpg', 'Painting of a stage spotlight cutting through blue haze',
       pg_temp.seed_agenda(s.starts_at, '[{"offset_hours":0,"duration_hours":1.5,"title":"Pitches","detail":""},{"offset_hours":1.5,"duration_hours":1.5,"title":"Networking","detail":""}]'::jsonb), '[]'::jsonb, 'Wallet-credit refund up to 24 hours before.', null,
       case when s.starts_at + make_interval(secs => 10800) <= now() then 'completed' else 'published' end, 77,
       now() - interval '21 days', now() - interval '14 days'
  from (select pg_temp.seed_at(11, '18:30') as starts_at) s
on conflict (id) do nothing;
insert into public.event_media (event_id, storage_path, kind, alt_text, sort_order)
select 'e1000000-0000-4000-8000-000000000015', 'seed/startup-pitch-night.jpg', 'cover', 'Painting of a stage spotlight cutting through blue haze', 0
 where not exists (select 1 from public.event_media where event_id = 'e1000000-0000-4000-8000-000000000015' and kind = 'cover');
insert into public.ticket_tiers (id, event_id, name, description, price_minor, currency, quantity,
                                 max_per_order, sort_order, sold)
values ('f1000000-0000-4000-8000-000000000151', 'e1000000-0000-4000-8000-000000000015', 'General', '', 50000, 'LKR', 200, 4, 0, 77)
on conflict (id) do nothing;
insert into public.event_settlements (event_id) values ('e1000000-0000-4000-8000-000000000015') on conflict (event_id) do nothing;

insert into public.events (id, organizer_id, category_id, venue_id, title, summary, description, format,
                           starts_at, ends_at, capacity, is_free, university, tags, cover_path, cover_alt,
                           agenda, speakers, refund_policy, online_url, status, seats_taken,
                           creation_fee_paid_at, published_at)
select 'e1000000-0000-4000-8000-000000000016', '6f1d0a3e-1c2b-4d5e-8f90-0a1b2c3d4e03', 'music', '7a2e0b4f-2d3c-4e6f-9a01-1b2c3d4e5f12', 'Lagoon Music Night', 'Folk and baila on the lagoon front', 'An evening of eastern folk songs and baila by the lagoon.', 'physical',
       s.starts_at, s.starts_at + make_interval(secs => 10800), 250, true, null, array['folk', 'baila', 'batticaloa']::text[], 'seed/lagoon-music-night.jpg', 'Painting of a lagoon at dusk with boats and lanterns',
       pg_temp.seed_agenda(s.starts_at, '[]'::jsonb), '[]'::jsonb, 'Free registration.', null,
       case when s.starts_at + make_interval(secs => 10800) <= now() then 'completed' else 'published' end, 210,
       now() - interval '21 days', now() - interval '14 days'
  from (select pg_temp.seed_at(-10, '18:30') as starts_at) s
on conflict (id) do nothing;
insert into public.event_media (event_id, storage_path, kind, alt_text, sort_order)
select 'e1000000-0000-4000-8000-000000000016', 'seed/lagoon-music-night.jpg', 'cover', 'Painting of a lagoon at dusk with boats and lanterns', 0
 where not exists (select 1 from public.event_media where event_id = 'e1000000-0000-4000-8000-000000000016' and kind = 'cover');

-- -----------------------------------------------------------------------------
-- Development user state: wallet (via a posted ledger top-up so the ledger and
-- the balance agree), monthly allowance usage, registrations, tickets, saved
-- events and a few notifications. Skipped if already seeded.
-- -----------------------------------------------------------------------------
do $seed$
declare
  v_dev uuid := 'b0000000-0000-4000-8000-0000000000aa';
  v_month date := private.colombo_month();
  v_reg uuid;
  v_ticket uuid;
  v_order uuid;
  v_starts timestamptz;
  v_created timestamptz;
begin
  if exists (select 1 from public.registrations where user_id = v_dev) then
    raise notice 'development user already seeded';
    return;
  end if;

  -- Wallet: balance changes only through the ledger.
  insert into public.wallet_ledger (user_id, entry_type, amount_minor, status, reference_type, description)
  values (v_dev, 'topup', 14000, 'posted', 'seed', 'LOCAL DEVELOPMENT seed top-up');

  -- Allowance used this calendar month (Asia/Colombo).
  insert into public.allowance_usage (user_id, month, used) values (v_dev, v_month, 13)
  on conflict (user_id, month) do update set used = excluded.used;

  -- Free registration: swiftui-workshop
  select starts_at into v_starts from public.events where id = 'e1000000-0000-4000-8000-000000000002';
  v_created := least(now() - interval '2 days', v_starts - interval '3 days');
  insert into public.registrations (event_id, user_id, status, kind, used_allowance, allowance_month,
                                    fee_minor, reference, created_at)
  values ('e1000000-0000-4000-8000-000000000002', v_dev, 'confirmed', 'free', true, private.colombo_month(v_created), 0,
          private.generate_registration_reference(), v_created)
  returning id into v_reg;
  insert into public.registration_answers (registration_id, question_id, value)
  select v_reg, (a ->> 'question_id')::uuid, a -> 'value' from jsonb_array_elements('[{"question_id":"20d69f82-756b-5729-9606-1403d1a582b1","value":true}]'::jsonb) a;
  v_ticket := private.issue_ticket(v_reg, 'e1000000-0000-4000-8000-000000000002', v_dev, null, null);
  if private.colombo_month(v_created) <> v_month then
    insert into public.allowance_usage (user_id, month, used) values (v_dev, private.colombo_month(v_created), 1)
    on conflict (user_id, month) do update set used = public.allowance_usage.used + 1;
  end if;
  if v_starts < now() then
    -- Past event: the development user attended.
    update public.tickets set status = 'checked_in', checked_in_at = v_starts + interval '20 minutes' where id = v_ticket;
    insert into public.check_ins (ticket_id, event_id, checked_in_at) values (v_ticket, 'e1000000-0000-4000-8000-000000000002', v_starts + interval '20 minutes');
  else
    insert into public.notifications (user_id, kind, title, body, event_id, data, created_at)
    values (v_dev, 'registration_confirmed', 'You''re registered', 'Native iOS with SwiftUI', 'e1000000-0000-4000-8000-000000000002',
            jsonb_build_object('registration_id', v_reg, 'ticket_id', v_ticket), v_created);
  end if;

  -- Free registration: open-source-day
  select starts_at into v_starts from public.events where id = 'e1000000-0000-4000-8000-000000000012';
  v_created := least(now() - interval '2 days', v_starts - interval '3 days');
  insert into public.registrations (event_id, user_id, status, kind, used_allowance, allowance_month,
                                    fee_minor, reference, created_at)
  values ('e1000000-0000-4000-8000-000000000012', v_dev, 'confirmed', 'free', true, private.colombo_month(v_created), 0,
          private.generate_registration_reference(), v_created)
  returning id into v_reg;
  v_ticket := private.issue_ticket(v_reg, 'e1000000-0000-4000-8000-000000000012', v_dev, null, null);
  if private.colombo_month(v_created) <> v_month then
    insert into public.allowance_usage (user_id, month, used) values (v_dev, private.colombo_month(v_created), 1)
    on conflict (user_id, month) do update set used = public.allowance_usage.used + 1;
  end if;
  if v_starts < now() then
    -- Past event: the development user attended.
    update public.tickets set status = 'checked_in', checked_in_at = v_starts + interval '20 minutes' where id = v_ticket;
    insert into public.check_ins (ticket_id, event_id, checked_in_at) values (v_ticket, 'e1000000-0000-4000-8000-000000000012', v_starts + interval '20 minutes');
  else
    insert into public.notifications (user_id, kind, title, body, event_id, data, created_at)
    values (v_dev, 'registration_confirmed', 'You''re registered', 'Open Source Community Day', 'e1000000-0000-4000-8000-000000000012',
            jsonb_build_object('registration_id', v_reg, 'ticket_id', v_ticket), v_created);
  end if;

  -- Free registration: lagoon-music-night
  select starts_at into v_starts from public.events where id = 'e1000000-0000-4000-8000-000000000016';
  v_created := least(now() - interval '2 days', v_starts - interval '3 days');
  insert into public.registrations (event_id, user_id, status, kind, used_allowance, allowance_month,
                                    fee_minor, reference, created_at)
  values ('e1000000-0000-4000-8000-000000000016', v_dev, 'confirmed', 'free', true, private.colombo_month(v_created), 0,
          private.generate_registration_reference(), v_created)
  returning id into v_reg;
  v_ticket := private.issue_ticket(v_reg, 'e1000000-0000-4000-8000-000000000016', v_dev, null, null);
  if private.colombo_month(v_created) <> v_month then
    insert into public.allowance_usage (user_id, month, used) values (v_dev, private.colombo_month(v_created), 1)
    on conflict (user_id, month) do update set used = public.allowance_usage.used + 1;
  end if;
  if v_starts < now() then
    -- Past event: the development user attended.
    update public.tickets set status = 'checked_in', checked_in_at = v_starts + interval '20 minutes' where id = v_ticket;
    insert into public.check_ins (ticket_id, event_id, checked_in_at) values (v_ticket, 'e1000000-0000-4000-8000-000000000016', v_starts + interval '20 minutes');
  else
    insert into public.notifications (user_id, kind, title, body, event_id, data, created_at)
    values (v_dev, 'registration_confirmed', 'You''re registered', 'Lagoon Music Night', 'e1000000-0000-4000-8000-000000000016',
            jsonb_build_object('registration_id', v_reg, 'ticket_id', v_ticket), v_created);
  end if;

  -- Paid ticket (1 x Lawn): jazz-under-the-stars. Counted inside the tier's seeded `sold`.
  insert into public.orders (user_id, event_id, kind, status, subtotal_minor, commission_minor, total_minor,
                             idempotency_key, answers, expires_at, paid_at, created_at)
  values (v_dev, 'e1000000-0000-4000-8000-000000000006', 'ticket', 'paid', 300000, (300000 * private.setting('commission_bps') + 5000) / 10000, 300000,
          'seed-jazz-under-the-stars-dev', '[]'::jsonb, now() - interval '6 days 23 hours', now() - interval '7 days', now() - interval '7 days')
  returning id into v_order;
  insert into public.order_items (order_id, tier_id, quantity, unit_price_minor) values (v_order, 'f1000000-0000-4000-8000-000000000061', 1, 300000);
  insert into public.payments (order_id, provider_payment_id, status_code, amount_minor, currency, method, outcome, notification)
  values (v_order, 'seed-jazz-under-the-stars', 2, 300000, 'LKR', 'TEST', 'paid', '{"note":"LOCAL DEVELOPMENT seed payment","status_code":"2"}'::jsonb);
  insert into public.registrations (event_id, user_id, status, kind, order_id, reference, created_at)
  values ('e1000000-0000-4000-8000-000000000006', v_dev, 'confirmed', 'paid', v_order, private.generate_registration_reference(), now() - interval '7 days')
  returning id into v_reg;
  v_ticket := private.issue_ticket(v_reg, 'e1000000-0000-4000-8000-000000000006', v_dev, 'f1000000-0000-4000-8000-000000000061', v_order);
  insert into public.notifications (user_id, kind, title, body, event_id, data, created_at)
  values (v_dev, 'ticket_issued', 'Your ticket is ready', 'Jazz Under the Stars', 'e1000000-0000-4000-8000-000000000006',
          jsonb_build_object('order_id', v_order, 'ticket_ids', jsonb_build_array(v_ticket)), now() - interval '7 days');
  -- expected commission for this seed order: 15000

  insert into public.saved_events (user_id, event_id) values (v_dev, 'e1000000-0000-4000-8000-000000000003') on conflict do nothing;
  insert into public.saved_events (user_id, event_id) values (v_dev, 'e1000000-0000-4000-8000-000000000004') on conflict do nothing;
  insert into public.saved_events (user_id, event_id) values (v_dev, 'e1000000-0000-4000-8000-000000000011') on conflict do nothing;

  insert into public.notifications (user_id, kind, title, body, data, created_at)
  values (v_dev, 'general', 'Welcome to Zuno', 'Discover events across Sri Lanka and keep your tickets in one place.',
          '{}'::jsonb, now() - interval '10 days');
end
$seed$;

reset timezone;
